# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

parameters:
  run_workflow_main:
    default: true
    type: boolean

jobs:
  build:
    docker:
      - image: circleci/node:16

    working_directory: /tmp/workspace

    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - run: yarn test

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - public
            - .firebaserc
            - firebase.json

  deploy:
    docker:
      - image: cimg/node:20

    working_directory: /tmp/workspace

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run: npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
      - run: npm install -g firebase-tools
      - run: /home/circleci/npm/bin/firebase deploy

workflows:
  version: 2
  main:
    when: << pipeline.parameters.run_workflow_main >>
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
