name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      CONTENTFUL_SPACE_ID: '${{ secrets.CONTENTFUL_SPACE_ID }}'
      CONTENTFUL_PREVIEW_KEY: '${{ secrets.CONTENTFUL_PREVIEW_KEY }}'
      CONTENTFUL_DELIVERY_KEY: '${{ secrets.CONTENTFUL_DELIVERY_KEY }}'
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_WEBSITE }}'
          projectId: zenker-portfolio
          channelId: live
